// AUTO-GENERATED by emit-sdk — do not edit.
// Source: plugin.json `action_types`. Run: just gen-plugins

package main

// GreetParams is the params shape for action "helloworld.greet (Greet)".
type GreetParams struct {
	Name *string `json:"name,omitempty"`
}

