// Code generated by branchkit-gen from plugin.json `action_types`. DO NOT EDIT.
// Regenerate from the plugin directory: branchkit-gen --plugin .

package main

import "github.com/branchkit/plugin-sdk-go"

// GreetParams is the params shape for action "helloworld.greet (Greet)".
type GreetParams struct {
	Name *string `json:"name,omitempty"`
}

// HandleGreet registers a typed handler for action "helloworld.greet (Greet)".
func HandleGreet(p *branchkit.Plugin, fn func(GreetParams, *branchkit.OnActionRequest) (any, error)) {
	branchkit.HandleActionTyped(p, "helloworld.greet", fn)
}
